### ISSUE TITLE
New Team Member Notes

### ISSUE THREAD

**Issue by tan-zhou** [hackforla/civic-opportunity#64]
### Overview
New team members providing feedbacks and notes about their onboarding experience.

### Action Items

- [ ] Review project one-sheet 
- [ ] Identify any questions
- [ ] Document questions for feedback

### Instructions
Link documents you have questions 
[Title of the document](url)

### Resources
[Project One-Sheet](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf)
[OKR Document](https://docs.google.com/spreadsheets/d/15Y3RkkoWC9GPilLF5G8IiS3cLYWs3ZiqtOXp2C--PvM/edit#gid=30376616)

**Comment by tan-zhou** [comment]
Comments

**Comment by ExperimentsInHonesty** [comment]
Q:  In the project one-pager, I wasn't sure what "VRMS" is referring to.
A: VRMS refers to to the [Volunteer Relationship Management Project](https://www.hackforla.org/projects/vrms)

Q:  In the project one-pager. I had problems understanding why the majority of initiatives identified were about career service without further elaboration from Bonnie and Ray.
A: I have added a few words to the one sheet to clarify.  And the one sheet could be improved by indicating which items are workforce development and which are Relationship bridge building.

Q:  I was looking for documents' that I can study myself in the project Google Drive, but there aren't many materials that are constructed for new onboarder's self-learning.
A: After discussion it is determined that all new team members will put their questions into this document and we will answer them here, so that we can start to build a document library for onboarding.

**Comment by rjdoria** [comment]
A retrospective:

How to get set up on the civicopportunity@hackforla.org email
- needed to coordinate with Tan and Ray to use 1Password and login (text verification)

How to get set up on Meetup group to draft event
- needed Bonnie to add to group and change membership to Assistant Organizer

**Comment by TaniaKhan04** [comment]
In the project one-pager, I was a bit unclear if the Project-Roadmap was meant for the Civic Opportunity team itself or for the people the team would be helping.

**Comment by rfambro2** [comment]
@TaniaKhan04 - I updated the One-Sheet to reflect our initiatives. Would love some feedback on how to communicate the roadmap a bit more clearly though. It's intended to track progress for the project/team...but it sounds like that isn't apparent right now.

**Comment by rfambro2** [comment]
Documenting @rjdoria feedback:

We should consider building out a process/journey for project inception (I.e. How can a new project idea be vetted? Google Form for new project ideas? Write a proposal for review? Bring in fundraising ideas and external clients/partnerships?)

**Comment by patrickm-tan** [comment]
Project One-Page:

- Should consider updating the project's 6 month road-map. Where are we as of 04/2021 (7 Months after)
- [Thought] I had trouble understanding this paragraph. Is this section explaining that we discovered that these solutions listed below are the best to provide in preparing the volunteers?

> "We have surfaced, and **trialed** the delivery of 1-to-1 solutions to meet the following **underserved** needs within our community of volunteers in the area of preparation and searching for employment."

- [Revision] Remove scale and (videos, tutorials, VRMS). They are listed as initiatives but are not explained in the initiatives section. So what are these? Also I believe that we aren't scaling these products, we are building them out currently? 

> "This project seeks to use technology solutions in order to scale these initiatives (videos, tutorials, VRMS, etc):" --> "This project aims to use these solutions in order to build out our initiatives (listed below)"

- Implement a How to join section? Providing the slack channel, and who to DM. (Although this is redundant if they are coming from a GitHub job boards)

**Comment by ExperimentsInHonesty** [comment]
@randall please review the above note for changes to the one sheet.

**Comment by ExperimentsInHonesty** [comment]
@patrickm-tan please look at the wiki

**Comment by Arjayellis** [comment]
@patrickm-tan please look at the wiki and
