### ISSUE TITLE
Creating Marketing Interest Form and make recruiting plan

### ISSUE THREAD

**Issue by tan-zhou** [hackforla/civic-opportunity#76]
### Overview
We need to create an interest form for marketing roles so that we can recruit and communicate with volunteers that are interested in marketing.  

### Action Items
- [x] Create Marketing Interest form in Role/Recruitment Folder
  - [x] Contact Info
  - [x] Timezone
  - [x] Availability 
  - [x] Project/Position Interests
  - [x] Experience Level 
  - [x] Specific tool knowledge 
- [x] Review the details about each ask with teammates and make necessary edits
- [x] Discuss with the team on how to respond 

### Resources/Instructions
- [Marketing Interest form](https://forms.gle/J8nJm6oEeGrzr1Eo8)
- [Role/Recruitment folder](https://drive.google.com/drive/folders/1LLqovq883cgU2n-yt8YsnoFlUUp4olgb?usp=sharing)
- [Project Recruiting Current Needs spreadsheet](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0) 
- [Marketing Recruitment Pipelines](https://docs.google.com/forms/d/e/1FAIpQLScDrgJHndp48GUbbpj4mlkbqYM0nuaU0Rr6WojKCXM9k9iNNA/viewform) | [Response Spreadsheet](https://docs.google.com/spreadsheets/d/19VBho1i-3kmteCUy-T0SsMu2NdblOblI_s2cVRxdC8U/edit#gid=1886028946)
- [Marketing Professionals Criteria](https://docs.google.com/document/d/1e_KoV9NTv42btfK0lj-G8_HG8h3vncjOkeAaXW6DOyg/edit#)
- [Messsaging](https://docs.google.com/document/d/1vmFPqFKBGcrblF83AZ9l8vw09m5X5srA0U-FcT1rENs/edit?usp=sharing)

**Comment by tan-zhou** [comment]
I created the initial Marketing interest form based on the form used for UXR. But role-specific questions about marketing are pending --- need to be created after discussing with the team.

**Comment by tan-zhou** [comment]
I updated the Marketing Interest form link used here. The previous link was to the editing version and would tell people to request access.

**Comment by tan-zhou** [comment]
{Placeholder for the marketing form outreach message}

**Comment by rfambro2** [comment]
Thanks @tan-zhou ! I used your message above to reach out to Mya. If we don't hear anything today, I'll just go ahead and post in one of the Marketing Slack channels myself. For documentation, see below for my message out to Mya:

Good evening @Mya Stark! My name is Ray Fambro and I am the Product Manager for the Civic Opportunity Project (a project focused on curating an intentional recruitment and professional development process for HfLA volunteers). We are currently looking to fill various Marketing roles for the majority of our project teams and @Bonnie tells me that you might be interested in helping us get the word out!

We'd like to post a link to our Marketing Interest Form in various channels and groups. I have a list of groups that I think we can ping...but maybe we just start by posting to one to mitigate responses in the beginning. In order to do this, we should reach out to the group administrator first.

**Here is some sample text that you could use to start the initial conversation:**
_"Hi, I volunteer at Hack for LA which provides volunteer opportunities for marketing & communication professionals from students to the experienced. These volunteers will receive free training from industry pros so that they can volunteer their time on cutting edge civic tech projects that directly impact the community and grow their resumes. We are currently looking for a series of marketing roles, both organizational & project level, and we encourage anybody who is interested in this opportunity to fill out this form: https://forms.gle/FRHH1hwMiZRTnjDVA
Also, would it be OK if I occasionally post any marketing & communication volunteer opportunities that come up in the future?"_

**Once given the green light, you can join the respective group and post this message:**
_"Hack for LA (HfLA) is looking for enthusiastic, civic-minded volunteers for a variety of marketing & communications roles on ongoing HfLA projects. You will have the opportunity to build professional skills by working with interdisciplinary teams while also increasing awareness of impactful civic-tech projects that serve our communities! Please fill out this form to indicate your interests: https://forms.gle/FRHH1hwMiZRTnjDVA"_

**Lastly, here is a doc of groups that I think we can target:**
 https://docs.google.com/spreadsheets/d/1-3dim1QogwYpHogQQ7Yd4rlMEHiOWuCK5Jx3yEkDGiE/edit#gid=0

**But for this effort, let's just start with OnlineGeniuses first:**
https://onlinegeniuses.com/

Let me know if this sounds like something that you'd be interested in doing Mya. Looking forward to working with you!

**Comment by rfambro2** [comment]
I posted in (2) Marketing Slack Channels on Sunday, November 15th @ 11:15am EST.
- Backlinks
- Growmance

Several of the remaining groups require admin approval before gaining admittance. My request for those is currently pending.

**Comment by rfambro2** [comment]
I've posted in additional Slack Groups:

- [ ] Online Geniuses
- [ ] CRO Growth Hacks

We now have 4 more people that filled out the Interest Form.

**Comment by rfambro2** [comment]
Adding Elle's Marketing Google Doc here for reference:

https://docs.google.com/document/d/1DyR0fg38tTq9hI6I4eBItVJUT0Xxg23yGV81rsQuFpQ/edit

**Comment by rfambro2** [comment]
Marketing Manager workshop invites have gone out. Will now need to reach out to the (2) Coordinators to set up workshop.

**Comment by tan-zhou** [comment]
@ExperimentsInHonesty @tan-zhou met with Elle on Friday's marketing meeting and decided to host an onboarding session for volunteers with management level experience. The onboarding is scheduled for 12/11.

**Comment by tan-zhou** [comment]
Messaging doc was created to document all civic opportunity project outbound mesassing

**Comment by ExperimentsInHonesty** [comment]
I had this queued up to commit.  Not sure why I had this queued up, maybe I was going to edit it.  I really have no idea.

Marketing outreach message:

Hi, I volunteer at Hack for LA which provides volunteer opportunities for marketing & communication professionals from students to the experienced. These volunteers will receive free training from industry pros so that they can volunteer their time on cutting edge civic tech projects that directly impact the community and grow their resumes. We are currently looking for a series of marketing roles, both organizational & project level, and we encourage anybody who is interested in this opportunity to fill out this form.

Also, would it be OK if I occasionally post any marketing & communication volunteer opportunities that come up in the future?

**Comment by tan-zhou** [comment]
I updated the link for the Marketing Recruitment Pipeline and response sheet.

**Comment by rfambro2** [comment]
Ray will re socialize Marketing onboarding Slack channels today (12/10)

**Comment by tan-zhou** [comment]
@ExperimentsInHonesty Hosted an onboarding for Marketing Coordinator on 21, but no one showed up.

**Comment by tan-zhou** [comment]
@rjdoria  Please refer to this issue for marketing setup

**Comment by ExperimentsInHonesty** [comment]
marketing onboarding
