### ISSUE TITLE
Create Process Document for UXR pilot project

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#83]
### Overview
We need a template to be able to launch a new pipeline quickly with predictable results.

### Action Items
- [x] Look at UXR Process
- [x] Define common steps
- [x] Propose format for documentation
- [ ] Document
- [ ] Review with team

### Goals
- [ ] To create a reusable process
- [ ] Document lessons learned/best practices (continued iteration)
- [ ] Identify capacity areas for development

### Resources/Instructions
Reference Issue #65 
- [UXR Process document](https://docs.google.com/document/d/10IibGu7sJGZtmKyZR6sfZF20vU-1YiniIKGGZ5KOvwk/edit?usp=sharing)

**Comment by tan-zhou** [comment]
I'd like to review the process draft with the team for I fear that I missed out on plenty of details of our process.

**Comment by tan-zhou** [comment]
@tan-zhou will create a flow chat based on the process document.

**Comment by ExperimentsInHonesty** [comment]
update from meeting: still working on this
eta: end of next week.

**Comment by tan-zhou** [comment]
Upon reviewing the most recent round of UX recruiting, the following areas could be improved:
Issue: 
- We were able to attract a big number of people to attend the onboarding session, but few of them have the matching experience for the open roles. 
Potential solves: 
- We need to be clearer in our messaging that the experience level we are looking for those opportunities.
-  We could manually vet respondents and assign experience people in a separate room for onboarding
- We could bring up the survey again and ask those who checked "managed others" to join a breakout room

Issue:
- We asked volunteers who didn't get matched with a role to join the UI/UX community of practice, but weren't able to actually start their training, because UI/UX CoP isn't ready to take on the coaching responsibility yet.  
Potential solves: 
- Model "Getting started" document after the product management one, and quickly testing that out in the next CoP meeting (Make an issue for this @tan-zhou )
- Creative more issues in UI/UX GitHub that is suitable for new joiners to take on as their first practice questions (Make an issue for this)

What's onboarding's job? 
Currently, the zoom onboarding has an immensurable list of things that it tries to achieve 
- **Familiarize** new volunteers with HfLA and CfA 
- **Teach** new volunteers of processes and COD at HfLA
- **Learn** about who new volunteers are and what they'd like to do
- **Match** then with projects and convert them into a committed state  
- **Set up** new volunteers on all the organizational tools (GitHub, Google Drive, Slack)
- **Guide** them on their next steps at Hack for LA
(not even the complete list)
Too much information for the first-run experience as a volunteer. 
Then how do we design the onboarding so we can indeed carry our new volunteers upwards on the path to retention and engagement? How can we support people through multiple events in their journey at Hack for LA?

**Comment by tan-zhou** [comment]
The next step: we will take the learning from UX pilots and use it to address issue #141 and #142

**Comment by tan-zhou** [comment]
I will organize and document this finding in our Wiki
